export const SET_COUNTRIES_INIT = 'SET_COUNTRIES_INIT';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SEARCHED_COUNTRIES = 'SEARCHED_COUNTRIES';
export const RESET_SEARCHED = 'RESET_SEARCHED';
export const SET_PROMISES = 'SET_PROMISES';
export const SET_TOP_TEN = 'SET_TOP_TEN';
export const SET_RATIO_COUNTRY = 'SET_RATIO_COUNTRY';